{% set name = "types-hdbcli" %}
{% set version = "2.19.0.20240310" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-hdbcli-{{ version }}.tar.gz
  sha256: e71b375301b9a3c43f578aadb5551b96fa6b80e9320de0cffc6460a7ac4f075e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/hdbcli-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\hdbcli-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for hdbcli
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxvolk
