{% set name = "types-hdbcli" %}
{% set version = "2.23.0.20250318" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d992bed289649d13cb0938e017eb98c443bdc28b20f53e6ef61c9af535a159b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/hdbcli-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\hdbcli-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for hdbcli
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxvolk
